/**
 * setup.js - Relay first-run setup
 * Generates .env and prints an iPhone Shortcut Bearer token.
 *
 * No OpenSSL.
 * No TLS certificates.
 * No extra npm packages beyond the existing project dependencies.
 */

"use strict";

const crypto = require("crypto");
const fs = require("fs");
const os = require("os");
const path = require("path");

const ENV_FILE = path.join(__dirname, ".env");
const TOKEN_FILE = path.join(__dirname, "relay-token.txt");

const RESET = process.argv.includes("--reset");

function main() {
  const env = loadEnvFile();

  if (RESET || !env.JWT_SECRET) {
    env.JWT_SECRET = crypto.randomBytes(64).toString("hex");
  }

  env.PORT = env.PORT || "3080";

  /**
   * Leave empty by default.
   * Recommended index.js behavior:
   * - If ALLOWED_SUBNET is empty, allow private LAN IPs.
   * - If ALLOWED_SUBNET is set, only allow that subnet.
   */
  env.ALLOWED_SUBNET = env.ALLOWED_SUBNET ?? "";

  env.JWT_MAX_AGE = env.JWT_MAX_AGE ?? "";
  env.RATE_LIMIT_MAX = env.RATE_LIMIT_MAX || "60";
  env.RATE_LIMIT_WINDOW_MS = env.RATE_LIMIT_WINDOW_MS || "60000";
  env.HELPER_MAX_BUFFER_MB = env.HELPER_MAX_BUFFER_MB || "220";
  env.CLIPBOARD_MAX_FILE_MB = env.CLIPBOARD_MAX_FILE_MB || "100";
  env.ALLOWED_FILE_ROOTS = env.ALLOWED_FILE_ROOTS ?? "";

  writeEnvFile(env);

  const token = createToken(env.JWT_SECRET);
  fs.writeFileSync(TOKEN_FILE, `Bearer ${token}\n`, "utf8");

  printSetupInfo(env, token);
}

function loadEnvFile() {
  if (!fs.existsSync(ENV_FILE)) return {};

  const content = fs.readFileSync(ENV_FILE, "utf8");
  const env = {};

  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();

    if (!trimmed || trimmed.startsWith("#")) continue;

    const match = trimmed.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (!match) continue;

    env[match[1]] = match[2];
  }

  return env;
}

function writeEnvFile(env) {
  const content = [
    "# Relay Server Configuration",
    "",
    "# Server port",
    `PORT=${env.PORT}`,
    "",
    "# JWT secret used to verify iPhone Shortcut requests",
    "# Generated by setup.js. Do not share this value.",
    `JWT_SECRET=${env.JWT_SECRET}`,
    "",
    "# Optional. Leave empty to allow private LAN IPs.",
    "# Examples:",
    "# ALLOWED_SUBNET=192.168.1.",
    "# ALLOWED_SUBNET=192.168.0.",
    `ALLOWED_SUBNET=${env.ALLOWED_SUBNET}`,
    "",
    "# Optional JWT max age.",
    "# Examples: 7d, 30d, 12h",
    "# Leave empty to allow non-expiring tokens.",
    `JWT_MAX_AGE=${env.JWT_MAX_AGE}`,
    "",
    "# Optional rate limit settings",
    `RATE_LIMIT_MAX=${env.RATE_LIMIT_MAX}`,
    `RATE_LIMIT_WINDOW_MS=${env.RATE_LIMIT_WINDOW_MS}`,
    "",
    "# Optional helper output buffer size in MB",
    `HELPER_MAX_BUFFER_MB=${env.HELPER_MAX_BUFFER_MB}`,
    "",
    "# Optional maximum copied file size for clipboard base64 transfer in MB",
    `CLIPBOARD_MAX_FILE_MB=${env.CLIPBOARD_MAX_FILE_MB}`,
    "",
    "# Optional semicolon-separated allowed file roots for GET /file",
    "# Leave empty to default to the user's home directory.",
    "# Example:",
    "# ALLOWED_FILE_ROOTS=C:\\Users\\YourName;D:\\Shared",
    `ALLOWED_FILE_ROOTS=${env.ALLOWED_FILE_ROOTS}`,
    ""
  ].join("\n");

  fs.writeFileSync(ENV_FILE, content, "utf8");
}

function createToken(secret) {
  let jwt;

  try {
    jwt = require("jsonwebtoken");
  } catch {
    console.error("");
    console.error("Missing dependency: jsonwebtoken");
    console.error("Run: npm install");
    console.error("");
    process.exit(1);
  }

  return jwt.sign(
    {
      app: "relay",
      device: "iphone"
    },
    secret
  );
}

function printSetupInfo(env, token) {
  const port = env.PORT;
  const hostname = os.hostname();
  const lanAddresses = getLanAddresses();

  console.log("");
  console.log("Relay setup completed.");
  console.log("");
  console.log("Server URL options:");
  console.log(`- http://${hostname}.local:${port}`);
  console.log(`- http://${hostname}:${port}`);

  for (const ip of lanAddresses) {
    console.log(`- http://${ip}:${port}`);
  }

  console.log("");
  console.log("Use one of the URLs above in your iPhone Shortcut.");
  console.log("Try the .local address first. If it does not work, use the IP address.");
  console.log("");
  console.log("Bearer Token:");
  console.log("--------------------------------------------------");
  console.log(`Bearer ${token}`);
  console.log("--------------------------------------------------");
  console.log("");
  console.log(`The token was also saved to: ${TOKEN_FILE}`);
  console.log("");
  console.log("Important:");
  console.log("- Do not commit .env");
  console.log("- Do not commit relay-token.txt");
  console.log("- If you run setup.js --reset, old iPhone Shortcut tokens will stop working.");
  console.log("");
}

function getLanAddresses() {
  const interfaces = os.networkInterfaces();
  const addresses = [];

  for (const details of Object.values(interfaces)) {
    for (const item of details || []) {
      const isIPv4 = item.family === "IPv4" || item.family === 4;

      if (!isIPv4 || item.internal) continue;
      if (!isPrivateIPv4(item.address)) continue;

      addresses.push(item.address);
    }
  }

  return addresses;
}

function isPrivateIPv4(ip) {
  return (
    ip.startsWith("10.") ||
    ip.startsWith("192.168.") ||
    /^172\.(1[6-9]|2\d|3[0-1])\./.test(ip)
  );
}

main();


